name: Q1 Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # JY :
    permissions : write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy README.md to Q1_archive_README.md
        run: cp README.md Q1_archive_README.md

      - name: Commit and push changes
        run: |
          git config --global user.name MatKim76
          git config --global user.email mateo.kim.sa@gmail.com
          git add Q1_archive_README.md
          git commit -m "Add Q1_archive_README.md"
          git push
