name: Q1 Workflow

on:
  push:
    branches:
      - main

jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy README.md to Q1_archive_README.md
        run: cp README.md Q1_archive_README.md

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add Q1_archive_README.md
          git commit -m "Add Q1_archive_README.md"
          git push
