name: Q2 Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-archive:
    # JY :
    permissions : write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Q2_archive_README.md
        run: |
          echo "Nom: Sa Prénom: Matéo" > Q2_archive_README.md
          echo "Date et Heure: $(date '+%Y-%m-%d %H:%M:%S')" >> Q2_archive_README.md
          cat README.md >> Q2_archive_README.md

      - name: Commit and push changes
        run: |
          git config --global user.name MatKim76
          git config --global user.email mateo.kim.sa@gmail.com
          git add Q2_archive_README.md
          git commit -m "Add Q2_archive_README.md"
          git push
