name: Q4 Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-archive:
    # JY :
    permissions : write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Q4_archive_date.txt
        run: |
          DATE=$(date '+%d-%m-%Y')
          echo "Nom: Sa Prénom: Matéo" > Q4_archive_${DATE}.txt
          cat Q4.java >> Q4_archive_${DATE}.txt

      - name: Commit and push changes
        run: |
          git config --global user.name MatKim76
          git config --global user.email mateo.kim.sa@gmail.com  
          git add Q4_archive_${DATE}.txt
          git commit -m "Add Q4_archive_${DATE}.txt"
          git push
